"""final rev

Revision ID: 4d5e0d78fb9c
Revises: 8f68d46fa231
Create Date: 2026-03-14 21:01:58.877983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5e0d78fb9c'
down_revision: Union[str, Sequence[str], None] = '8f68d46fa231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True))
    op.drop_column('user', 'status')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
